author: Çağan Seyrek
description: 3rd-year computer engineering student who loves full-stack web development and the open-source.
keywords: "personal website, portfolio, web development, full-stack"

github_profile: https://github.com/caganseyrek

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude:
  - testfile.html